// ============================================
// StellarIDE — Artifact ZIP Packager
// Bundles ABI + TS client + README into ZIP
// ============================================

use std::io::{Cursor, Write};
use zip::{write::FileOptions, ZipWriter};
use crate::errors::{AppError, AppResult};

pub struct ArtifactBundle {
    pub contract_id: String,
    pub abi_json: String,
    pub ts_client: String,
    pub network: String,
}

pub fn create_zip(bundle: &ArtifactBundle) -> AppResult<Vec<u8>> {
    let mut buf = Vec::new();

    {
        // ── ZipWriter borrows &mut cursor, dropped before buf is returned ──
        let mut cursor = Cursor::new(&mut buf);
        let mut zip = ZipWriter::new(&mut cursor);

        let options = FileOptions::default()
            .compression_method(zip::CompressionMethod::Deflated);

        // ── ABI JSON ──────────────────────────────
        zip.start_file("abi.json", options)
            .map_err(|e| AppError::Internal(format!("ZIP error: {}", e)))?;
        zip.write_all(bundle.abi_json.as_bytes())
            .map_err(|e| AppError::Internal(format!("ZIP write error: {}", e)))?;

        // ── TypeScript client ─────────────────────
        zip.start_file("client.ts", options)
            .map_err(|e| AppError::Internal(format!("ZIP error: {}", e)))?;
        zip.write_all(bundle.ts_client.as_bytes())
            .map_err(|e| AppError::Internal(format!("ZIP write error: {}", e)))?;

        // ── README ────────────────────────────────
        let readme = generate_readme(&bundle.contract_id, &bundle.network);
        zip.start_file("README.md", options)
            .map_err(|e| AppError::Internal(format!("ZIP error: {}", e)))?;
        zip.write_all(readme.as_bytes())
            .map_err(|e| AppError::Internal(format!("ZIP write error: {}", e)))?;

        zip.finish()
            .map_err(|e| AppError::Internal(format!("ZIP finish error: {}", e)))?;
    } // ── cursor + zip dropped here, buf is free ──

    Ok(buf)
}

fn generate_readme(contract_id: &str, network: &str) -> String {
    let fence = "```";
    format!(
        "# StellarIDE Contract Artifacts\n\
         \n\
         ## Contract Details\n\
         - **Contract ID**: `{contract_id}`\n\
         - **Network**: `{network}`\n\
         \n\
         ## Files\n\
         - `abi.json`  — Contract ABI\n\
         - `client.ts` — Auto-generated TypeScript client\n\
         \n\
         ## Usage\n\
         {fence}typescript\n\
         import client from \"./client\";\n\
         const result = await client.yourFunction(args);\n\
         {fence}\n\
         \n\
         Generated by [StellarIDE](https://stellaride.io)\n",
        contract_id = contract_id,
        network = network,
        fence = fence,
    )
}
