export const STELLAR_DARK_THEME = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'keyword', foreground: '9b6dff', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: '9b6dff', fontStyle: 'bold' },
    { token: 'keyword.other', foreground: '9b6dff' },
    { token: 'string', foreground: '3dd68c' },
    { token: 'string.quoted', foreground: '3dd68c' },
    { token: 'comment', foreground: '555555', fontStyle: 'italic' },
    { token: 'comment.line', foreground: '555555', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '555555', fontStyle: 'italic' },
    { token: 'number', foreground: 'f5c842' },
    { token: 'type', foreground: '4f9eff' },
    { token: 'type.identifier', foreground: '4f9eff' },
    { token: 'identifier', foreground: 'e8e8e8' },
    { token: 'attribute', foreground: 'ff8c42' },
    { token: 'macro', foreground: 'ff8c42' },
    { token: 'variable', foreground: 'e8e8e8' },
    { token: 'variable.other', foreground: 'e8e8e8' },
    { token: 'operator', foreground: 'e8e8e8' },
    { token: 'delimiter', foreground: '888888' },
    { token: 'punctuation', foreground: '888888' },
  ],
  colors: {
    'editor.background': '#0d0d0d',
    'editor.foreground': '#e8e8e8',
    'editor.lineHighlightBackground': '#161616',
    'editor.selectionBackground': '#4f9eff33',
    'editor.inactiveSelectionBackground': '#4f9eff22',
    'editorLineNumber.foreground': '#555555',
    'editorLineNumber.activeForeground': '#888888',
    'editorCursor.foreground': '#4f9eff',
    'editorIndentGuide.background': '#2a2a2a',
    'editorIndentGuide.activeBackground': '#3a3a3a',
    'editorWhitespace.foreground': '#2a2a2a',
    'editorRuler.foreground': '#2a2a2a',
    'editorBracketMatch.background': '#4f9eff22',
    'editorBracketMatch.border': '#4f9eff55',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#2a2a2a88',
    'scrollbarSlider.hoverBackground': '#3a3a3a88',
    'scrollbarSlider.activeBackground': '#4a4a4a88',
    'minimap.background': '#0d0d0d',
    'panel.background': '#111111',
    'panelTitle.activeBorder': '#4f9eff',
  },
}

export const EDITOR_OPTIONS = {
  fontSize: 13,
  fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
  fontLigatures: true,
  lineHeight: 1.6,
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  smoothScrolling: true,
  cursorBlinking: 'smooth',
  cursorStyle: 'line',
  wordWrap: 'on',
  bracketPairColorization: { enabled: true },
  automaticLayout: true,
  formatOnPaste: true,
  formatOnType: false,
  tabSize: 4,
  insertSpaces: true,
  renderWhitespace: 'selection',
  lineNumbers: 'on',
  renderLineHighlight: 'line',
  scrollbar: {
    vertical: 'auto',
    horizontal: 'auto',
    verticalScrollbarSize: 6,
    horizontalScrollbarSize: 6,
  },
  padding: { top: 12, bottom: 12 },
  overviewRulerBorder: false,
  hideCursorInOverviewRuler: true,
  contextmenu: true,
  mouseWheelZoom: false,
  links: true,
  suggest: { snippetsPreventQuickSuggestions: false },
}
